import {
    FIELD_TYPE_TEXT,
    FIELD_TYPE_SELECT,
    FIELD_TYPE_CHECKBOX,
    FIELD_TYPE_GRID,
    FIELD_TYPE_FILE,
    FIELD_TYPE_DIVIDER,
    FIELD_TYPE_DISPLAY,
    FIELD_TYPE_RICHTEXT,
    FIELD_TYPE_CHECKTREE,
} from '@/constants/fields.constant'

import type { FormFieldConfig } from '@/@types/forms'

const formConfig: FormFieldConfig = {
    config: {
        prefix: 'project',
        table: 'projects',
        singularName: 'Projeto',
        pluralName: 'Projetos',
        icon: 'toolbox',
        permissions: {
            delete: true,
            add: true,
            edit: true,
            read: false,
            browse: false,
        },
        tabs: [
            { key: 'main', label: 'Principal' },
            { key: 'historic-situation', label: 'Histórico de Situações' },
            { key: 'appointment', label: 'Apontamentos' },
        ],
        version: '05-09-2024|10-55-45',
    },
    fields: [
        {
            name: 'project_code',
            order: 1,
            width: 3,
            browserOrder: 1,
            browserWidth: 1,
            type: FIELD_TYPE_TEXT,
            canBrowse: true,
            canMobile: true,
            canRead: true,
            canEdit: true,
            canAdd: true,
            label: 'Código do Projeto',
            required: true,
            tabs: ['main'],
            showOnTop: false,
        },
        {
            name: 'project_files',
            order: 61,
            width: 12,
            browserWidth: 6,
            type: FIELD_TYPE_FILE,
            canBrowse: false,
            canRead: true,
            canEdit: true,
            canAdd: true,
            label: 'Anexos',
            tabs: ['main'],
            showOnTop: false,
            multifiles: true,
            showQuestions: true,
        },
        {
            name: 'project_obs',
            order: 65,
            width: 12,
            browserWidth: 6,
            mobileOrder: 8,
            mobileWidth: 10,
            type: FIELD_TYPE_RICHTEXT,
            canBrowse: false,
            canMobileInfo: true,
            canRead: true,
            canEdit: true,
            canAdd: true,
            label: 'Observações',
            tabs: ['main'],
            showOnTop: false,
        },
        {
            name: 'project_startedby_fk_user_id',
            order: 28,
            width: 4,
            browserOrder: 3,
            browserWidth: 3,
            type: FIELD_TYPE_SELECT,
            canBrowse: true,
            canRead: true,
            canEdit: true,
            canAdd: true,
            label: 'Iniciado Por',
            hidden: false,
            readonly: true,
            tabs: ['main'],
            showOnTop: false,
            api: {
                method: 'GET',
                uses: [{ type: 'prop' }],
                url: '/api/v1/users/select',
            },
            displayLabel: 'user_name',
            alias: 'userStart',
            browseLabel: 'userStart.user_name',
        },
        {
            name: 'project_users',
            order: 47,
            width: 10,
            browserWidth: 6,
            type: FIELD_TYPE_CHECKTREE,
            canBrowse: false,
            canRead: true,
            canEdit: true,
            canAdd: true,
            label: 'Usuarios Responsaveis',
            tabs: ['main'],
            showOnTop: false,
            api: {
                method: 'GET',
                uses: [
                    {
                        type: 'field',
                        field: 'project_involveds',
                        as: 'data',
                    },
                ],
                url: '/api/v1/users/select',
            },
            useActive: true,
            displayLabel:
                "users.user_name + '-' + users.user_cpf_cnpj + '-' + users.role.role_name",
            alias: 'users',
            browseLabel:
                "users.user_name + '-' + users.user_cpf_cnpj + '-' + users.role.role_name",
        },
        {
            name: 'project_div1',
            order: 36,
            width: 12,
            browserWidth: 6,
            type: FIELD_TYPE_DIVIDER,
            canBrowse: false,
            canMobile: false,
            canRead: true,
            canEdit: true,
            canAdd: true,
            label: 'Dados do Cliente',
            tabs: ['main'],
            showOnTop: false,
        },
    ],
}

export default formConfig
